FROM python:3.8-slim

ENV PIP_VERSION 20.3.3

RUN apt-get update && \
    apt-get install make && \
    pip install -U pip==${PIP_VERSION}

WORKDIR /app

COPY requirements-dev.txt .
RUN pip install -r requirements-dev.txt

COPY satellite satellite
COPY app.py Makefile .flake8 ./

ENTRYPOINT ["make", "lint", "test"]
