"""New RuleEntry field: transformer_config_map.

Revision ID: 946eac86c154
Revises: a7c1dfd362a2
Create Date: 2020-12-16 14:46:10.859349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946eac86c154'
down_revision = 'a7c1dfd362a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule_entries', sa.Column('transformer_config_map', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule_entries', 'transformer_config_map')
    # ### end Alembic commands ###
