"""New Alias field: expires_at.

Revision ID: a7c1dfd362a2
Revises: a11347ab93be
Create Date: 2020-12-14 14:49:31.118133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c1dfd362a2'
down_revision = 'a11347ab93be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aliases', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aliases', 'expires_at')
    # ### end Alembic commands ###
