"""Drop Alias.generatortype constraint.

Revision ID: e5af5cb8c05c
Revises: 946eac86c154
Create Date: 2021-01-12 11:45:41.321834

"""
from alembic import op

from satellite.db.models.alias import Alias
from satellite.db.models.route import RuleEntry


# revision identifiers, used by Alembic.
revision = 'e5af5cb8c05c'
down_revision = '946eac86c154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(Alias.__tablename__)
    op.drop_table(RuleEntry.__tablename__)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
