"""Drop enum constaints.

Revision ID: fe38630490f9
Revises: 71e95818e76e
Create Date: 2021-02-08 17:13:46.342033

"""
from alembic import op

from satellite.db.models.alias import Alias
from satellite.db.models.route import RuleEntry


# revision identifiers, used by Alembic.
revision = 'fe38630490f9'
down_revision = '71e95818e76e'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table(Alias.__tablename__)
    op.drop_table(RuleEntry.__tablename__)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
